/* Generated By:JavaCC: Do not edit this line. BlockBuilderConstants.java */
package cs524BlockBuilder;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BlockBuilderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int LBRACKET = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int SQUOTE = 15;
  /** RegularExpression Id. */
  int DQUOTE = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int DEFINE = 20;
  /** RegularExpression Id. */
  int SOCKET = 21;
  /** RegularExpression Id. */
  int ID = 22;
  /** RegularExpression Id. */
  int VOLUME = 23;
  /** RegularExpression Id. */
  int CONNECT = 24;
  /** RegularExpression Id. */
  int BALL = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "\":\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"define\"",
    "\"socket\"",
    "\"id\"",
    "\"volume\"",
    "\"connectsTo\"",
    "\"at\"",
  };

}
